import { GeneratedFile } from "@/lib/types";

export interface GitHubUser {
  login: string;
  name: string;
  avatar_url: string;
  html_url: string;
}

export interface ScaffoldRepoOptions {
  repoName: string;
  description: string;
  isPrivate: boolean;
  files: GeneratedFile[];
}

export interface ScaffoldProgress {
  stage: "idle" | "validating" | "creating_repo" | "committing_files" | "completed" | "error";
  message: string;
  progressPercent: number;
  repoUrl?: string;
  error?: string;
}

export async function validateGitHubToken(token: string): Promise<{ valid: boolean; user?: GitHubUser; error?: string }> {
  try {
    const res = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${token.trim()}`,
        Accept: "application/vnd.github.v3+json",
      },
    });

    if (!res.ok) {
      if (res.status === 401) {
        return { valid: false, error: "Invalid GitHub Personal Access Token (PAT)." };
      }
      const data = await res.json().catch(() => ({}));
      return { valid: false, error: data.message || `GitHub error ${res.status}` };
    }

    const user: GitHubUser = await res.json();
    return { valid: true, user };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Network error connecting to GitHub API";
    return { valid: false, error: message };
  }
}

export async function scaffoldGitHubRepo(
  token: string,
  options: ScaffoldRepoOptions,
  onProgress?: (progress: ScaffoldProgress) => void
): Promise<{ success: boolean; repoUrl?: string; error?: string }> {
  const cleanToken = token.trim();
  const headers = {
    Authorization: `Bearer ${cleanToken}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  try {
    // 1. Validate Token & User
    onProgress?.({
      stage: "validating",
      message: "Verifying GitHub credentials & permissions...",
      progressPercent: 15,
    });

    const userRes = await fetch("https://api.github.com/user", { headers });
    if (!userRes.ok) {
      throw new Error("Invalid or expired GitHub Personal Access Token.");
    }
    const user = await userRes.json();
    const owner = user.login;

    // 2. Create Repository
    onProgress?.({
      stage: "creating_repo",
      message: `Creating repository ${owner}/${options.repoName}...`,
      progressPercent: 35,
    });

    const createRepoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: options.repoName,
        description: options.description || "Production DevOps Stack generated by DevOps Project Generator",
        private: options.isPrivate,
        auto_init: true, // Creates initial commit on main branch
      }),
    });

    if (!createRepoRes.ok) {
      const errorData = await createRepoRes.json().catch(() => ({}));
      const msg = errorData.errors?.[0]?.message || errorData.message || `Failed to create repository (${createRepoRes.status})`;
      throw new Error(msg);
    }

    const repoData = await createRepoRes.json();
    const repoUrl = repoData.html_url;

    // Brief delay to allow GitHub internal replication of the initial commit
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // 3. Get Initial Commit Reference
    onProgress?.({
      stage: "committing_files",
      message: "Preparing Git tree and manifest blobs...",
      progressPercent: 55,
    });

    const refRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/ref/heads/main`, { headers });
    if (!refRes.ok) {
      throw new Error("Failed to retrieve default branch reference from GitHub.");
    }
    const refData = await refRes.json();
    const baseCommitSha = refData.object.sha;

    // Get Base Commit to read base tree sha
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/commits/${baseCommitSha}`, { headers });
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // 4. Create Blobs for All Generated Files
    const textFiles = options.files.filter((f) => f.type === "file" && f.content && f.content.length > 0);
    const treeItems: Array<{ path: string; mode: "100644"; type: "blob"; sha: string }> = [];

    let processed = 0;
    for (const file of textFiles) {
      // Normalize path to strip leading project folder if present
      const cleanPath = file.path.includes("/") ? file.path.substring(file.path.indexOf("/") + 1) : file.path;

      const blobRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/blobs`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          content: file.content,
          encoding: "utf-8",
        }),
      });

      if (blobRes.ok) {
        const blobData = await blobRes.json();
        treeItems.push({
          path: cleanPath,
          mode: "100644",
          type: "blob",
          sha: blobData.sha,
        });
      }

      processed++;
      const currentPercent = 55 + Math.round((processed / textFiles.length) * 30);
      onProgress?.({
        stage: "committing_files",
        message: `Committed ${processed}/${textFiles.length} manifests...`,
        progressPercent: currentPercent,
      });
    }

    // 5. Create Git Tree
    const newTreeRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/trees`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeItems,
      }),
    });

    if (!newTreeRes.ok) {
      throw new Error("Failed to construct Git tree on GitHub.");
    }
    const newTreeData = await newTreeRes.json();

    // 6. Create Commit
    const finalCommitRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/commits`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: "feat: scaffold production devops architecture via DevOps Project Generator",
        tree: newTreeData.sha,
        parents: [baseCommitSha],
      }),
    });

    if (!finalCommitRes.ok) {
      throw new Error("Failed to generate Git commit on GitHub.");
    }
    const finalCommitData = await finalCommitRes.json();

    // 7. Update main branch reference to new commit
    const updateRefRes = await fetch(`https://api.github.com/repos/${owner}/${options.repoName}/git/refs/heads/main`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({
        sha: finalCommitData.sha,
        force: true,
      }),
    });

    if (!updateRefRes.ok) {
      throw new Error("Failed to update branch head.");
    }

    onProgress?.({
      stage: "completed",
      message: `Repository created and initial commit pushed!`,
      progressPercent: 100,
      repoUrl,
    });

    return { success: true, repoUrl };
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : "An unexpected error occurred during GitHub scaffolding";
    onProgress?.({
      stage: "error",
      message: errorMessage,
      progressPercent: 0,
      error: errorMessage,
    });
    return { success: false, error: errorMessage };
  }
}

export function buildGitHubCliScript(projectName: string, isPrivate: boolean = true): string {
  const vis = isPrivate ? "--private" : "--public";
  return `gh repo create ${projectName} ${vis} --source=. --remote=origin --push`;
}

export function buildFullGitSetupScript(projectName: string, isPrivate: boolean = true): string {
  const vis = isPrivate ? "--private" : "--public";
  return `# 1. Initialize git and commit files
git init
git add .
git commit -m "feat: initial production devops scaffold"
git branch -M main

# 2. Create remote repo & push using GitHub CLI
gh repo create ${projectName} ${vis} --source=. --remote=origin --push`;
}
