# Makefile for smoke-test
# Generated by DevOps Project Generator

.PHONY: help install test lint format clean build deploy start stop logs health

# Default target
.DEFAULT_GOAL := help

# Variables
PROJECT_NAME := smoke-test
ENVIRONMENT := production
PYTHON := python3
VENV := venv
ACTIVATE := $(VENV)/bin/activate

# Colors
BLUE := \033[36m
GREEN := \033[32m
YELLOW := \033[33m
RED := \033[31m
RESET := \033[0m

help: ## Show this help message
	@echo "$(BLUE)smoke-test - DevOps Project$(RESET)"
	@echo "$(GREEN)Available commands:$(RESET)"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(YELLOW)%-20s$(RESET) %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# Development Setup
install: ## Install dependencies and setup environment
	@echo "$(GREEN)Setting up development environment...$(RESET)"
	@if [ ! -d "$(VENV)" ]; then \
		$(PYTHON) -m venv $(VENV); \
		echo "$(BLUE)Virtual environment created$(RESET)"; \
	fi
	@. $(ACTIVATE); pip install --upgrade pip
	@. $(ACTIVATE); pip install -r app/sample-app/requirements.txt
	@echo "$(GREEN)Dependencies installed$(RESET)"

install-dev: ## Install development dependencies
	@echo "$(GREEN)Installing development dependencies...$(RESET)"
	@. $(ACTIVATE); pip install black flake8 mypy pytest pytest-cov pre-commit
	@. $(ACTIVATE); pre-commit install
	@echo "$(GREEN)Development dependencies installed$(RESET)"

# Code Quality
lint: ## Run linting
	@echo "$(GREEN)Running linting...$(RESET)"
	@. $(ACTIVATE); flake8 app/sample-app/ --count --select=E9,F63,F7,F82 --show-source --statistics
	@. $(ACTIVATE); flake8 app/sample-app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
	@. $(ACTIVATE); mypy app/sample-app/ --ignore-missing-imports

format: ## Format code with black
	@echo "$(GREEN)Formatting code...$(RESET)"
	@. $(ACTIVATE); black app/sample-app/ scripts/
	@echo "$(GREEN)Code formatted$(RESET)"

# Testing
test: ## Run tests
	@echo "$(GREEN)Running tests...$(RESET)"
	@. $(ACTIVATE); pytest app/sample-app/ --cov=app/sample-app --cov-report=term-missing --cov-report=html

test-watch: ## Run tests in watch mode
	@echo "$(GREEN)Running tests in watch mode...$(RESET)"
	@. $(ACTIVATE); pytest app/sample-app/ --cov=app/sample-app -f

# Security
security-scan: ## Run security scans
	@echo "$(GREEN)Running security scans...$(RESET)"
	@. $(ACTIVATE); safety check
	@. $(ACTIVATE); bandit -r app/sample-app/




# Application Management
start: ## Start the application
	@echo "$(GREEN)Starting application...$(RESET)"
	@. $(ACTIVATE); python app/sample-app/main.py

stop: ## Stop the application
	@echo "$(GREEN)Stopping application...$(RESET)"
	@pkill -f "main.py" || true

restart: stop start ## Restart the application

logs: ## Show application logs
	@tail -f logs/app.log

# Health checks
health: ## Check application health
	@echo "$(GREEN)Checking application health...$(RESET)"
	@echo "$(YELLOW)Health checks not enabled$(RESET)"

ready: ## Check application readiness
	@echo "$(GREEN)Checking application readiness...$(RESET)"
	@echo "$(YELLOW)Readiness checks not enabled$(RESET)"

# Deployment
deploy: ## Deploy application
	@echo "$(GREEN)Deploying application...$(RESET)"
	@chmod +x scripts/deploy.sh
	@./scripts/deploy.sh deploy

rollback: ## Rollback deployment
	@echo "$(RED)Rolling back deployment...$(RESET)"
	@chmod +x scripts/deploy.sh
	@./scripts/deploy.sh rollback

# Setup
setup: ## Setup project environment
	@echo "$(GREEN)Setting up project...$(RESET)"
	@chmod +x scripts/setup.sh
	@./scripts/setup.sh

# Cleanup
clean: ## Clean up temporary files
	@echo "$(GREEN)Cleaning up...$(RESET)"
	@find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	@find . -type f -name "*.pyc" -delete
	@find . -type f -name "*.pyo" -delete
	@find . -type f -name ".coverage" -delete
	@find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
	@find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	@find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
	@echo "$(GREEN)Cleanup completed$(RESET)"

clean-all: clean ## Clean everything including Docker
	@echo "$(RED)Cleaning everything...$(RESET)"
	@rm -rf $(VENV)
	@echo "$(GREEN)Full cleanup completed$(RESET)"

# Monitoring

# Development helpers
dev-setup: install install-dev ## Setup full development environment
	@echo "$(GREEN)Development environment setup complete$(RESET)"

dev-run: ## Run in development mode
	@echo "$(GREEN)Running in development mode...$(RESET)"
	@ENV=development DEBUG=true . $(ACTIVATE); python app/sample-app/main.py

prod-run: ## Run in production mode
	@echo "$(GREEN)Running in production mode...$(RESET)"
	@ENV=production DEBUG=false . $(ACTIVATE); python app/sample-app/main.py

# Version and info
version: ## Show version information
	@echo "$(BLUE)smoke-test$(RESET)"
	@echo "Environment: $(ENVIRONMENT)"
	@echo "Python: $(shell $(PYTHON) --version)"
	@if [ -d ".git" ]; then echo "Git: $(shell git describe --tags --always 2>/dev/null || echo 'unknown')"; fi

info: ## Show project information
	@echo "$(BLUE)Project Information:$(RESET)"
	@echo "Name: $(PROJECT_NAME)"
	@echo "Environment: $(ENVIRONMENT)"
	@echo "CI/CD: github-actions"
	@echo "Infrastructure: aws-vpc-eks"
	@echo "Deployment: rolling"
	@echo "Observability: prometheus-grafana"
	@echo "Security: nist-csf"
	@echo ""
	@echo "$(BLUE)Available endpoints:$(RESET)"
	@echo "- Info: http://localhost:8000/info"

# Quick commands
quick-test: ## Quick test run
	@. $(ACTIVATE); pytest app/sample-app/ -v

quick-lint: ## Quick lint check
	@. $(ACTIVATE); flake8 app/sample-app/ --max-line-length=127

quick-format: ## Quick format
	@. $(ACTIVATE); black app/sample-app/ --line-length=127

# CI/CD helpers
ci-test: ## Run CI tests
	@echo "$(GREEN)Running CI tests...$(RESET)"
	@make lint
	@make test
	@make security-scan

ci-build: ## Run CI build
	@echo "$(GREEN)Running CI build...$(RESET)"
	@make clean
	@make install
	@make ci-test

# Backup and restore
backup: ## Backup configuration and data
	@echo "$(GREEN)Creating backup...$(RESET)"
	@mkdir -p backups
	@tar -czf backups/backup-$(shell date +%Y%m%d_%H%M%S).tar.gz \
		.env \
		k8s/ \
		deploy/ \
		infra/ \
		monitoring/ \
		security/ \
		scripts/ \
		Makefile
	@echo "$(GREEN)Backup created$(RESET)"

list-backups: ## List available backups
	@echo "$(BLUE)Available backups:$(RESET)"
	@ls -la backups/ 2>/dev/null || echo "No backups found"

# Documentation
docs: ## Generate documentation
	@echo "$(GREEN)Generating documentation...$(RESET)"
	@. $(ACTIVATE); pip install sphinx
	@if [ ! -d "docs" ]; then mkdir docs; fi
	@sphinx-quickstart docs --quiet --no-prompt --project="$(PROJECT_NAME)" --author="DevOps Team" --version="1.0"
	@echo "$(GREEN)Documentation generated in docs/$(RESET)"

# Performance
perf-test: ## Run performance tests
	@echo "$(GREEN)Running performance tests...$(RESET)"
	@if command -v ab > /dev/null; then \
		ab -n 1000 -c 10 http://localhost:8000/health; \
	else \
		echo "$(YELLOW)Apache Bench (ab) not found. Install it to run performance tests.$(RESET)"; \
	fi

load-test: ## Run load tests
	@echo "$(GREEN)Running load tests...$(RESET)"
	@if command -v hey > /dev/null; then \
		hey -n 1000 -c 20 http://localhost:8000/health; \
	else \
		echo "$(YELLOW)hey not found. Install it to run load tests.$(RESET)"; \
	fi