import { ProjectConfig } from "@/lib/types";

export function generateMermaidCode(config: ProjectConfig): string {
  const ciLabel = formatLabel(config.ci);
  const infraLabel = formatLabel(config.infra);
  const deployLabel = formatLabel(config.deploy);
  const pipelineLabel = formatLabel(config.pipeline);
  const securityLabel = formatLabel(config.security);
  const obsLabel = formatLabel(config.observability);
  const envList = config.envs === "single" ? ["Production"] : config.envs.split(",");

  const envNodes = envList
    .map((env, i) => `    Env${i}["${env.trim().toUpperCase()} Environment"]`)
    .join("\n");

  return `%% Architecture Topology Generated by DevOps Project Architect
%% Project: ${config.projectName}
flowchart TD
  classDef default fill:#ffffff,stroke:#000000,stroke-width:1px,color:#000000;
  classDef accent fill:#000000,stroke:#000000,stroke-width:2px,color:#ffffff;
  classDef group fill:#f5f5f5,stroke:#000000,stroke-width:2px,color:#000000;

  Dev["Developer Workstation"]:::default -->|"git push"| SCM["Source Control Repository"]:::default
  SCM -->|"Webhook Trigger"| CI["${ciLabel}"]:::accent

  subgraph SecurityGate ["Quality & Compliance Gates (${securityLabel})"]
    direction TB
    CI --> Build["Build & Tests\\n(${pipelineLabel})"]:::default
    CI --> SecAudit["Security Vulnerability Scan\\n(${securityLabel})"]:::default
    Build --> ImgBuild["OCI Container Build"]:::default
    SecAudit --> SignImg["Cosign Image Signing"]:::default
  end

  ImgBuild --> Registry["OCI Container Registry"]:::default
  SignImg --> Registry

  subgraph CloudTopology ["Infrastructure & Orchestration (${infraLabel})"]
    direction TB
    Registry --> K8s["Cluster Compute & Pods\\n(${infraLabel})"]:::accent
    IaC["Declarative IaC\\n(Terraform / Manifests)"] -.->|"Provisions"| K8s
  end

  subgraph DeployPhase ["Deployment Strategy (${deployLabel})"]
    direction TB
    K8s --> Strategy["${deployLabel} Engine"]:::accent
  end

  subgraph EnvsTopology ["Target Environments"]
    direction LR
${envNodes}
  end

  Strategy --> EnvsTopology

  subgraph Telemetry ["Observability & Auditing (${obsLabel})"]
    direction LR
    EnvsTopology -.-> Collector["Metrics Collector\\n(${obsLabel})"]:::default
    Collector --> Alerts["Live Dashboards & Alerts"]:::default
  end
`;
}

function formatLabel(val: string): string {
  if (!val) return "Standard";
  return val
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
