import { ProjectConfig, GeneratedFile } from '@/lib/types';
import { normalizeProjectName } from '../file-utils';

// Generate realistic application files
export function generateRealisticApplicationFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const projectName = normalizeProjectName(config.projectName);
  
  // Unit tests
  files.push({
    path: `${projectName}/tests/test_main.py`,
    content: `"""
Unit tests for ${config.projectName} application
Generated by DevOps Project Generator v2.0.0
"""

import pytest
import json
import sys
import os

# Add the app directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'app'))

from main import app

@pytest.fixture
def client():
    """Test client fixture"""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_health_check(client):
    """Test health check endpoint"""
    response = client.get('/health')
    assert response.status_code == 200
    
    data = json.loads(response.data)
    assert data['status'] == 'healthy'
    assert data['service'] == '${config.projectName}'
    assert 'version' in data
    assert 'checks' in data

def test_metrics_endpoint(client):
    """Test metrics endpoint"""
    response = client.get('/metrics')
    assert response.status_code == 200
    assert 'text/plain' in response.content_type

def test_api_data_get(client):
    """Test GET /api/data endpoint"""
    response = client.get('/api/data')
    assert response.status_code == 200
    
    data = json.loads(response.data)
    assert 'message' in data
    assert 'timestamp' in data
    assert 'version' in data

def test_api_data_post(client):
    """Test POST /api/data endpoint"""
    test_data = {'key': 'value', 'number': 42}
    response = client.post('/api/data', 
                          json=test_data,
                          content_type='application/json')
    assert response.status_code == 201
    
    data = json.loads(response.data)
    assert data['received'] == test_data
    assert data['status'] == 'processed'

def test_api_data_post_invalid(client):
    """Test POST /api/data with invalid data"""
    response = client.post('/api/data', 
                          data='invalid json',
                          content_type='application/json')
    assert response.status_code == 400

if __name__ == '__main__':
    pytest.main([__file__])`,
    type: "file"
  });

  // Integration tests
  files.push({
    path: `${projectName}/tests/test_integration.py`,
    content: `"""
Integration tests for ${config.projectName} application
Generated by DevOps Project Generator v2.0.0
"""

import pytest
import requests
import time
import subprocess
import signal
import os

class TestApplicationIntegration:
    """Integration tests for the application"""
    
    @classmethod
    def setup_class(cls):
        """Setup test environment"""
        # Start the application in background
        cls.app_process = subprocess.Popen([
            'python', 'app/main.py'
        ], cwd=os.path.dirname(os.path.dirname(__file__)))
        
        # Wait for application to start
        time.sleep(3)
        
        cls.base_url = 'http://localhost:8080'
    
    @classmethod
    def teardown_class(cls):
        """Cleanup test environment"""
        if hasattr(cls, 'app_process'):
            cls.app_process.terminate()
            cls.app_process.wait()
    
    def test_health_check_integration(self):
        """Test health check endpoint integration"""
        response = requests.get(f'{self.base_url}/health', timeout=5)
        assert response.status_code == 200
        
        data = response.json()
        assert data['status'] == 'healthy'
        assert 'checks' in data
    
    def test_metrics_integration(self):
        """Test metrics endpoint integration"""
        response = requests.get(f'{self.base_url}/metrics', timeout=5)
        assert response.status_code == 200
        assert 'http_requests_total' in response.text
    
    def test_api_workflow(self):
        """Test complete API workflow"""
        # Test GET request
        response = requests.get(f'{self.base_url}/api/data', timeout=5)
        assert response.status_code == 200
        
        # Test POST request
        test_data = {'test': 'integration', 'timestamp': time.time()}
        response = requests.post(f'{self.base_url}/api/data', 
                               json=test_data, timeout=5)
        assert response.status_code == 201
        
        data = response.json()
        assert data['received'] == test_data

if __name__ == '__main__':
    pytest.main([__file__, '-v'])`,
    type: "file"
  });

  return files;
}
