import { ProjectConfig, GeneratedFile } from '@/lib/types';
import { normalizeProjectName } from '../file-utils';

// Generate realistic script files
export function generateRealisticScriptFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const projectName = normalizeProjectName(config.projectName);
  
  // Setup script
  files.push({
    path: `${projectName}/scripts/setup.sh`,
    content: `#!/bin/bash
# Setup script for ${config.projectName}
# Generated by DevOps Project Generator v2.0.0

set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
    echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    
    # Check kubectl if using Kubernetes
    if command -v kubectl &> /dev/null; then
        log_info "kubectl found"
    else
        log_warn "kubectl not found. Kubernetes deployment may not work."
    fi
    
    # Check Terraform if using infrastructure as code
    if command -v terraform &> /dev/null; then
        log_info "Terraform found"
    else
        log_warn "Terraform not found. Infrastructure as code may not work."
    fi
    
    log_info "Prerequisites check completed."
}

# Setup environment
setup_environment() {
    log_info "Setting up environment..."
    
    # Create .env file if it doesn't exist
    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            cp .env.example .env
            log_info "Created .env file from .env.example"
        else
            log_warn ".env.example not found. Creating basic .env file."
            cat > .env << EOF
PORT=8080
LOG_LEVEL=INFO
ENVIRONMENT=development
EOF
        fi
    else
        log_info ".env file already exists"
    fi
    
    # Create necessary directories
    mkdir -p logs
    mkdir -p data
    mkdir -p backups
    
    log_info "Environment setup completed."
}

# Build Docker images
build_images() {
    log_info "Building Docker images..."
    
    # Build main application
    docker build -t ${projectName}:latest .
    
    if [ \$? -eq 0 ]; then
        log_info "Docker image built successfully"
    else
        log_error "Failed to build Docker image"
        exit 1
    fi
}

# Run initial tests
run_tests() {
    log_info "Running initial tests..."
    
    # Run unit tests
    docker run --rm ${projectName}:latest python -m pytest tests/ -v
    
    if [ \$? -eq 0 ]; then
        log_info "Tests passed successfully"
    else
        log_warn "Some tests failed. Check the output above."
    fi
}

# Main setup function
main() {
    log_info "Starting setup for ${config.projectName}..."
    
    check_prerequisites
    setup_environment
    build_images
    run_tests
    
    log_info "Setup completed successfully!"
    log_info "You can now run the application with: make run"
}

# Run main function
main "\$@"`,
    type: "file"
  });

  // Deployment script
  files.push({
    path: `${projectName}/scripts/deploy.sh`,
    content: `#!/bin/bash
# Deployment script for ${config.projectName}
# Generated by DevOps Project Generator v2.0.0

set -euo pipefail

# Configuration
PROJECT_NAME="${projectName}"
DOCKER_REGISTRY="\${DOCKER_REGISTRY:-localhost:5000}"
VERSION="\${VERSION:-latest}"
ENVIRONMENT="\${ENVIRONMENT:-staging}"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

# Logging functions
log_info() {
    echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
    echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Validate environment
validate_environment() {
    log_info "Validating deployment environment: \$ENVIRONMENT"
    
    case \$ENVIRONMENT in
        staging|production|development)
            log_info "Environment \$ENVIRONMENT is valid"
            ;;
        *)
            log_error "Invalid environment: \$ENVIRONMENT"
            log_error "Valid environments: staging, production, development"
            exit 1
            ;;
    esac
}

# Build and push Docker image
build_and_push() {
    log_info "Building and pushing Docker image..."
    
    # Build image
    docker build -t \${DOCKER_REGISTRY}/\${PROJECT_NAME}:\${VERSION} .
    
    # Tag as latest
    docker tag \${DOCKER_REGISTRY}/\${PROJECT_NAME}:\${VERSION} \${DOCKER_REGISTRY}/\${PROJECT_NAME}:latest
    
    # Push to registry
    if [[ "\$DOCKER_REGISTRY" != "localhost:5000" ]]; then
        docker push \${DOCKER_REGISTRY}/\${PROJECT_NAME}:\${VERSION}
        docker push \${DOCKER_REGISTRY}/\${PROJECT_NAME}:latest
        log_info "Image pushed to registry"
    else
        log_info "Using local registry, skipping push"
    fi
}

# Deploy to Kubernetes
deploy_kubernetes() {
    log_info "Deploying to Kubernetes..."
    
    if ! command -v kubectl &> /dev/null; then
        log_error "kubectl not found. Cannot deploy to Kubernetes."
        exit 1
    fi
    
    # Apply namespace if it doesn't exist
    kubectl create namespace \${PROJECT_NAME}-\${ENVIRONMENT} --dry-run=client -o yaml | kubectl apply -f -
    
    # Apply deployment configurations
    if [ -d "deploy/k8s/\${ENVIRONMENT}" ]; then
        kubectl apply -f deploy/k8s/\${ENVIRONMENT}/ -n \${PROJECT_NAME}-\${ENVIRONMENT}
        log_info "Kubernetes deployment applied"
    else
        log_warn "No Kubernetes configurations found for \$ENVIRONMENT"
    fi
    
    # Wait for deployment to be ready
    kubectl rollout status deployment/\${PROJECT_NAME} -n \${PROJECT_NAME}-\${ENVIRONMENT} --timeout=300s
    
    log_info "Kubernetes deployment completed"
}

# Deploy using Docker Compose (for development)
deploy_docker_compose() {
    log_info "Deploying with Docker Compose..."
    
    if [ -f "docker-compose.yml" ]; then
        export COMPOSE_PROJECT_NAME=\${PROJECT_NAME}-\${ENVIRONMENT}
        export VERSION=\${VERSION}
        
        docker-compose up -d
        log_info "Docker Compose deployment completed"
    else
        log_warn "docker-compose.yml not found"
    fi
}

# Health check after deployment
health_check() {
    log_info "Performing health check..."
    
    # Wait for application to start
    sleep 10
    
    # Check health endpoint
    if command -v curl &> /dev/null; then
        if curl -f http://localhost:8080/health > /dev/null 2>&1; then
            log_info "Health check passed"
        else
            log_warn "Health check failed"
        fi
    else
        log_warn "curl not found, skipping health check"
    fi
}

# Main deployment function
main() {
    log_info "Starting deployment of \${PROJECT_NAME} to \${ENVIRONMENT}..."
    
    validate_environment
    build_and_push
    
    case \$ENVIRONMENT in
        development)
            deploy_docker_compose
            ;;
        staging|production)
            deploy_kubernetes
            ;;
    esac
    
    health_check
    
    log_info "Deployment completed successfully!"
}

# Run main function
main "\$@"`,
    type: "file"
  });

  // Health check script
  files.push({
    path: `${projectName}/scripts/health-check.sh`,
    content: `#!/bin/bash
# Health check script for ${config.projectName}
# Generated by DevOps Project Generator v2.0.0

set -euo pipefail

# Configuration
PROJECT_NAME="${projectName}"
HEALTH_URL="\${HEALTH_URL:-http://localhost:8080/health}"
TIMEOUT="\${TIMEOUT:-30}"
RETRIES="\${RETRIES:-3}"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

# Logging functions
log_info() {
    echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
    echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Check if service is healthy
check_health() {
    local attempt=1
    
    while [ \$attempt -le \$RETRIES ]; do
        log_info "Health check attempt \$attempt/\$RETRIES..."
        
        if command -v curl &> /dev/null; then
            # Use curl for health check
            response=\$(curl -s -o /dev/null -w "%{http_code}" --max-time \$TIMEOUT "\$HEALTH_URL" || echo "000")
            
            if [ "\$response" = "200" ]; then
                log_info "Health check passed (HTTP 200)"
                return 0
            else
                log_warn "Health check failed (HTTP \$response)"
            fi
        elif command -v wget &> /dev/null; then
            # Use wget as fallback
            if wget -q --spider --timeout=\$TIMEOUT "\$HEALTH_URL" 2>/dev/null; then
                log_info "Health check passed"
                return 0
            else
                log_warn "Health check failed"
            fi
        else
            log_error "Neither curl nor wget available for health check"
            return 1
        fi
        
        if [ \$attempt -lt \$RETRIES ]; then
            log_info "Waiting 5 seconds before retry..."
            sleep 5
        fi
        
        attempt=\$((attempt + 1))
    done
    
    log_error "Health check failed after \$RETRIES attempts"
    return 1
}

# Check service dependencies
check_dependencies() {
    log_info "Checking service dependencies..."
    
    # Check database connectivity (example)
    # if command -v psql &> /dev/null; then
    #     if psql "\$DATABASE_URL" -c "SELECT 1;" > /dev/null 2>&1; then
    #         log_info "Database connectivity: OK"
    #     else
    #         log_warn "Database connectivity: FAILED"
    #     fi
    # fi
    
    # Check external API connectivity (example)
    # if command -v curl &> /dev/null; then
    #     if curl -f "\$EXTERNAL_API_URL/health" > /dev/null 2>&1; then
    #         log_info "External API connectivity: OK"
    #     else
    #         log_warn "External API connectivity: FAILED"
    #     fi
    # fi
    
    log_info "Dependency checks completed"
}

# Check system resources
check_resources() {
    log_info "Checking system resources..."
    
    # Check disk space
    disk_usage=\$(df . | awk 'NR==2 {print \$5}' | sed 's/%//')
    if [ \$disk_usage -lt 80 ]; then
        log_info "Disk usage: \$disk_usage% (OK)"
    else
        log_warn "Disk usage: \$disk_usage% (HIGH)"
    fi
    
    # Check memory usage
    if command -v free &> /dev/null; then
        memory_usage=\$(free | awk 'NR==2{printf "%.0f", \$3*100/\$2}')
        if [ \$memory_usage -lt 80 ]; then
            log_info "Memory usage: \$memory_usage% (OK)"
        else
            log_warn "Memory usage: \$memory_usage% (HIGH)"
        fi
    fi
    
    # Check CPU load
    if command -v uptime &> /dev/null; then
        load_avg=\$(uptime | awk -F'load average:' '{print \$2}' | awk '{print \$1}' | sed 's/,//')
        log_info "CPU load average: \$load_avg"
    fi
}

# Generate health report
generate_report() {
    local status=\$1
    local timestamp=\$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    cat > health-report-\$(date +%Y%m%d-%H%M%S).json << EOF
{
    "service": "\${PROJECT_NAME}",
    "timestamp": "\${timestamp}",
    "status": "\${status}",
    "checks": {
        "health_endpoint": "\${HEALTH_URL}",
        "dependencies": "checked",
        "resources": "checked"
    }
}
EOF
    
    log_info "Health report generated"
}

# Main health check function
main() {
    log_info "Starting health check for \${PROJECT_NAME}..."
    
    check_dependencies
    check_resources
    
    if check_health; then
        generate_report "healthy"
        log_info "Overall health status: HEALTHY"
        exit 0
    else
        generate_report "unhealthy"
        log_error "Overall health status: UNHEALTHY"
        exit 1
    fi
}

# Run main function
main "\$@"`,
    type: "file"
  });

  return files;
}
